name: UnicomTask

on:
  push:
    branches: main
  gollum:
  workflow_dispatch:
  schedule:
    - cron: '0 14 * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'
        check-latest: true
    - uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ~/.AutoSignMachine
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - name: Verification
      run: |
        ls -la ~/.AutoSignMachine/
        cat ~/.AutoSignMachine/*.txt || true
        cat ~/.AutoSignMachine/*.json || true
    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: Install dependencies
      run: |
        npm install
    - name: Build and publish
      env:
        USERS_UNICOM_CONFIG: ${{ secrets.USERS_UNICOM_CONFIG }}
      run: |
        echo "$USERS_UNICOM_CONFIG" > ./config/.env
        cat ./config/.env
        node index.js unicom
